"""add_tiempo_preparacion

Revision ID: 386f2a5b4d1a
Revises: aab01d585704
Create Date: 2026-02-21 10:10:59.419079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386f2a5b4d1a'
down_revision: Union[str, Sequence[str], None] = 'aab01d585704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tiempo_preparacion', sa.Integer(), nullable=True, comment='Tiempo estimado de preparación en cocina (minutos)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tiempo_preparacion')
    # ### end Alembic commands ###
