"""kitchen_kanban

Revision ID: 4a24f48e6aa6
Revises: cf051ffc2fb3
Create Date: 2026-02-14 10:05:55.315950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a24f48e6aa6'
down_revision: Union[str, Sequence[str], None] = 'cf051ffc2fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'preparing', 'ready', name='item_state_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_states_id'), 'order_item_states', ['id'], unique=False)
    op.drop_index(op.f('idx_audit_logs_action'), table_name='global_audit_logs')
    op.drop_index(op.f('idx_audit_logs_created'), table_name='global_audit_logs')
    op.drop_index(op.f('ix_global_audit_logs_action'), table_name='global_audit_logs')
    op.drop_index(op.f('ix_global_audit_logs_created_at'), table_name='global_audit_logs')
    op.drop_index(op.f('ix_global_audit_logs_id'), table_name='global_audit_logs')
    op.drop_table('global_audit_logs')
    op.alter_column('companies', 'trial_ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('companies', 'suspended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('order_items', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('kitchen_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('kitchen_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('kitchen_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('kitchen_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('kitchen_notes', sa.String(length=500), nullable=True))
    op.alter_column('orders', 'tip',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('products', sa.Column('prep_time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'prep_time_minutes')
    op.alter_column('orders', 'tip',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('orders', 'kitchen_notes')
    op.drop_column('orders', 'kitchen_completed_at')
    op.drop_column('orders', 'kitchen_started_at')
    op.drop_column('orders', 'kitchen_accepted_at')
    op.drop_column('orders', 'kitchen_received_at')
    op.drop_column('order_items', 'prep_time_minutes')
    op.alter_column('companies', 'suspended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('companies', 'trial_ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('global_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('super_admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('affected_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['affected_company_id'], ['companies.id'], name=op.f('global_audit_logs_affected_company_id_fkey')),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], name=op.f('global_audit_logs_super_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('global_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_global_audit_logs_id'), 'global_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_global_audit_logs_created_at'), 'global_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_audit_logs_action'), 'global_audit_logs', ['action'], unique=False)
    op.create_index(op.f('idx_audit_logs_created'), 'global_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'global_audit_logs', ['action'], unique=False)
    op.drop_index(op.f('ix_order_item_states_id'), table_name='order_item_states')
    op.drop_table('order_item_states')
    # ### end Alembic commands ###
