"""Add reservations table

Revision ID: 4d2a5f0df30f
Revises: e939f0ef476b
Create Date: 2026-03-14 11:11:26.475851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d2a5f0df30f'
down_revision: Union[str, Sequence[str], None] = 'e939f0ef476b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_audit_logs_action'), table_name='global_audit_logs')
    op.drop_index(op.f('ix_global_audit_logs_created_at'), table_name='global_audit_logs')
    op.drop_index(op.f('ix_global_audit_logs_id'), table_name='global_audit_logs')
    op.drop_table('global_audit_logs')
    op.add_column('reservations', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('reservations', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('reservations', sa.Column('number_of_people', sa.Integer(), nullable=False))
    op.add_column('reservations', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('reservations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_reservation_company_date'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_id_empresa'), table_name='reservations')
    op.drop_constraint(op.f('reservations_id_empresa_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_id_table_fkey'), 'reservations', type_='foreignkey')
    op.drop_constraint(op.f('reservations_id_customer_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reservations', 'id_empresa')
    op.drop_column('reservations', 'reservation_date')
    op.drop_column('reservations', 'arrival_time')
    op.drop_column('reservations', 'id_customer')
    op.drop_column('reservations', 'id_table')
    op.drop_column('reservations', 'customer_phone')
    op.drop_column('reservations', 'party_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('party_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('id_table', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('id_customer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('arrival_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('reservations', sa.Column('reservation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('id_empresa', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_id_customer_fkey'), 'reservations', 'customers', ['id_customer'], ['id'])
    op.create_foreign_key(op.f('reservations_id_table_fkey'), 'reservations', 'tables', ['id_table'], ['id'])
    op.create_foreign_key(op.f('reservations_id_empresa_fkey'), 'reservations', 'companies', ['id_empresa'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_reservations_id_empresa'), 'reservations', ['id_empresa'], unique=False)
    op.create_index(op.f('ix_reservation_company_date'), 'reservations', ['id_empresa', 'reservation_date'], unique=False)
    op.alter_column('reservations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('reservations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('reservations', 'phone')
    op.drop_column('reservations', 'number_of_people')
    op.drop_column('reservations', 'time')
    op.drop_column('reservations', 'date')
    op.drop_column('reservations', 'company_id')
    op.create_table('global_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('super_admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('affected_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['affected_company_id'], ['companies.id'], name=op.f('global_audit_logs_affected_company_id_fkey')),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], name=op.f('global_audit_logs_super_admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('global_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_global_audit_logs_id'), 'global_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_global_audit_logs_created_at'), 'global_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_global_audit_logs_action'), 'global_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
