"""add_default_notes_to_products

Revision ID: 72813e10b0c5
Revises: a5b3c7d9e1f2
Create Date: 2026-03-17 16:08:39.597507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72813e10b0c5'
down_revision: Union[str, Sequence[str], None] = 'a5b3c7d9e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('default_notes', sa.String(), nullable=True, comment='Sugerencias o instrucciones por defecto (ej. Servir caliente)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'default_notes')
    # ### end Alembic commands ###
