"""add_subtotal_to_payments

Revision ID: 82be560b44f7
Revises: b55d2602c7d2
Create Date: 2026-02-07 21:21:27.710310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82be560b44f7'
down_revision: Union[str, Sequence[str], None] = 'b55d2602c7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.add_column('payments', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE payments SET subtotal = total_amount - tip_amount")
    op.alter_column('payments', 'subtotal', nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'processed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'processed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'subtotal')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    # ### end Alembic commands ###
