"""Add aplica_impuesto to Order

Revision ID: 8a0e3dd37ef7
Revises: f1a2b3c4d5e6
Create Date: 2026-03-24 09:48:18.081715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a0e3dd37ef7'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_notes_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.add_column('orders', sa.Column('aplica_impuesto', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_payments_invoice_number'), table_name='payments')
    op.create_index(op.f('ix_payments_numero_factura'), 'payments', ['numero_factura'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_numero_factura'), table_name='payments')
    op.create_index(op.f('ix_payments_invoice_number'), 'payments', ['numero_factura'], unique=True)
    op.drop_column('orders', 'aplica_impuesto')
    op.create_table('credit_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_empresa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_nc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cancelado_por', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por'], ['users.id'], name=op.f('credit_notes_cancelado_por_fkey')),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id'], name=op.f('credit_notes_id_empresa_fkey')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('credit_notes_payment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_notes_pkey')),
    sa.UniqueConstraint('numero_nc', name=op.f('credit_notes_numero_nc_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('payment_id', name=op.f('credit_notes_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_credit_notes_id'), 'credit_notes', ['id'], unique=False)
    # ### end Alembic commands ###
