"""Add telefono and modules to users

Revision ID: a16dda2ac823
Revises: 386f2a5b4d1a
Create Date: 2026-03-07 10:46:49.152500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16dda2ac823'
down_revision: Union[str, Sequence[str], None] = '386f2a5b4d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'tables', ['id_mesa'], ['id'])
    op.add_column('users', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('users', sa.Column('modules', sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modules')
    op.drop_column('users', 'telefono')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
