"""Update_tables_module_structure

Revision ID: a7941310e599
Revises: 97fb25e235ef
Create Date: 2026-02-03 15:16:07.699245

"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a7941310e599'
down_revision: Union[str, Sequence[str], None] = '97fb25e235ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('status', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('location', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tables', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('tables', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tables', 'number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_tables_qr_code'), 'tables', ['qr_code'], unique=True)
    op.create_index(op.f('ix_tables_status'), 'tables', ['status'], unique=False)
    op.drop_column('tables', 'is_occupied')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('is_occupied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tables_status'), table_name='tables')
    op.drop_index(op.f('ix_tables_qr_code'), table_name='tables')
    op.alter_column('tables', 'number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tables', 'updated_at')
    op.drop_column('tables', 'created_at')
    op.drop_column('tables', 'is_active')
    op.drop_column('tables', 'qr_code')
    op.drop_column('tables', 'location')
    op.drop_column('tables', 'status')
    # ### end Alembic commands ###
