"""Update Order model with OrderStatus enum and closed_at

Revision ID: d6254f027fcc
Revises: a7941310e599
Create Date: 2026-02-03 16:19:38.052842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6254f027fcc'
down_revision: Union[str, Sequence[str], None] = 'a7941310e599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Clean old data to avoid Enum casting errors
    op.execute("DELETE FROM order_items")
    op.execute("DELETE FROM orders")

    # Create Enum type manually if needed for Postgres, though SQLAlchemy might handle it.
    # We will let the alter_column do it but ensuring data is empty first.
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Abierto', 'En Preparación', 'Entregado', 'Cerrado', 'Cancelado', name='orderstatus'),
               existing_nullable=True,
               postgresql_using='status::orderstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('ABIERTO', 'EN_PREPARACION', 'ENTREGADO', 'CERRADO', 'CANCELADO', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('orders', 'closed_at')
    # ### end Alembic commands ###
