"""Update Role model

Revision ID: da2d08903339
Revises: 72813e10b0c5
Create Date: 2026-03-21 10:39:56.999753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2d08903339'
down_revision: Union[str, Sequence[str], None] = '72813e10b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reservations_id_empresa_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'companies', ['id_empresa'], ['id'])
    op.add_column('roles', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('roles', sa.Column('id_empresa', sa.Integer(), nullable=True))
    
    # Handle existing rows
    op.execute("UPDATE roles SET id_empresa = (SELECT MIN(id) FROM companies) WHERE id_empresa IS NULL")
    op.execute("DELETE FROM roles WHERE id_empresa IS NULL")
    
    op.alter_column('roles', 'id_empresa', nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_id_empresa'), 'roles', ['id_empresa'], unique=False)
    op.create_unique_constraint('uq_role_name_empresa', 'roles', ['name', 'id_empresa'])
    op.create_foreign_key(None, 'roles', 'companies', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint('uq_role_name_empresa', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_id_empresa'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'id_empresa')
    op.drop_column('roles', 'permissions')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_id_empresa_fkey'), 'reservations', 'companies', ['id_empresa'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
