"""add_personal_data_fields

Revision ID: e939f0ef476b
Revises: a16dda2ac823
Create Date: 2026-03-07 11:32:17.518609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e939f0ef476b'
down_revision: Union[str, Sequence[str], None] = 'a16dda2ac823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cedula', sa.String(), nullable=True))
    op.add_column('users', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('users', sa.Column('foto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto')
    op.drop_column('users', 'direccion')
    op.drop_column('users', 'cedula')
    # ### end Alembic commands ###
